'use client';

import { motion } from 'framer-motion';
import { ShieldCheck, AlertCircle, BookOpen, Quote, ExternalLink, CheckCircle2, XCircle } from 'lucide-react';
import { useAppContext } from '@/components/ThemeProvider';
import { t } from '@/lib/i18n';

const LIMITATIONS = [
  {
    icon: <XCircle className="w-4 h-4" aria-hidden="true" />,
    color: 'var(--danger)',
    title: 'Jagrat is NOT Swami Vivekananda',
    body: 'Jagrat is a software application. It does not channel, represent, simulate, or speak as Swami Vivekananda. Any resemblance to his personal style in the AI Reflection layer is coincidental and not intended as impersonation.',
  },
  {
    icon: <XCircle className="w-4 h-4" aria-hidden="true" />,
    color: 'var(--danger)',
    title: 'AI Interpretations Can Be Wrong',
    body: "The Layer 3 (AI Reflection) text is generated by a language model applying Vivekananda's documented philosophy to your stated context. It may misinterpret nuance, miss cultural context, or oversimplify complex inner states. Always use your own judgment.",
  },
  {
    icon: <XCircle className="w-4 h-4" aria-hidden="true" />,
    color: 'var(--danger)',
    title: 'Not a Mental Health Service',
    body: 'Jagrat is a philosophical reflection tool, not a licensed mental health service, therapist, or crisis counselor. It is not designed to diagnose, treat, or manage mental health conditions. For professional support, consult a qualified mental health practitioner or call Tele-MANAS: 14416.',
  },
  {
    icon: <AlertCircle className="w-4 h-4" aria-hidden="true" />,
    color: 'var(--gold-accent)',
    title: 'Quote Coverage is Finite',
    body: 'The verified quote database covers a carefully curated selection from the Complete Works of Swami Vivekananda (Vols. I–VIII, Advaita Ashrama). Not every authentic teaching is indexed. A "not found" result does not mean the quote is necessarily inauthentic — only that it falls outside our current verification scope.',
  },
  {
    icon: <AlertCircle className="w-4 h-4" aria-hidden="true" />,
    color: 'var(--gold-accent)',
    title: 'Language Translations Are Approximate',
    body: 'Hindi, Bengali, Marathi, Tamil, and Telugu UI strings are human-crafted translations of the English source. Verbatim Vivekananda quotes in non-English languages should always be cross-referenced with their original English source texts to verify fidelity.',
  },
];

const CITATION_RULES = [
  'Every quote displayed must come from the Complete Works of Swami Vivekananda (Advaita Ashrama, 8 Volumes) or authenticated correspondence published by the Ramakrishna Math.',
  'No quote may be displayed without a volume, section, and page reference.',
  'Paraphrased or approximate content must never be presented in the Documented Teaching (Layer 2) card.',
  'Any quote that cannot be verified to source level is rejected from the database entirely — it is not displayed as "unverified" within the chat flow.',
  'The Layer 3 AI Reflection card must always carry the label "AI Reflection — Not Swami Vivekananda" and must never co-mingle its generated text with the verbatim quote.',
];

const SOURCES = [
  { title: 'Complete Works of Swami Vivekananda (8 Volumes)', org: 'Advaita Ashrama, Mayavati', url: 'https://belurmath.org/complete-works-of-swami-vivekananda/' },
  { title: 'Inspired Talks', org: 'Ramakrishna-Vivekananda Center', url: 'https://www.ramakrishna.org' },
  { title: 'Letters of Swami Vivekananda', org: 'Advaita Ashrama', url: 'https://belurmath.org' },
  { title: 'Belur Math Quote Fact-Check Portal', org: 'Ramakrishna Math & Mission', url: 'https://belurmath.org' },
];

const cardVariants = {
  hidden: { opacity: 0, y: 16 },
  visible: (i: number) => ({
    opacity: 1, y: 0,
    transition: { delay: i * 0.08, duration: 0.4, ease: 'easeOut' as const },
  }),
};

export default function HonestyPage() {
  const { lang } = useAppContext();

  return (
    <div className="max-w-3xl mx-auto px-4 py-8 space-y-10">

      {/* ── Header ── */}
      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.4 }}
        className="space-y-2"
      >
        <div className="flex items-center gap-3">
          <div
            className="w-10 h-10 rounded-xl flex items-center justify-center"
            style={{ background: 'var(--saffron-soft)', border: '1px solid var(--card-border)' }}
            aria-hidden="true"
          >
            <ShieldCheck className="w-5 h-5" style={{ color: 'var(--saffron-primary)' }} />
          </div>
          <div>
            <h1 className="text-2xl font-bold" style={{ color: 'var(--text-primary)' }}>
              {t(lang, 'honesty_title')}
            </h1>
            <p className="text-sm" style={{ color: 'var(--text-muted)' }}>
              {t(lang, 'honesty_subtitle')}
            </p>
          </div>
        </div>
      </motion.div>

      {/* ── Core Commitment Box ── */}
      <motion.div
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ delay: 0.1, duration: 0.4 }}
        className="p-6 rounded-2xl"
        style={{
          background: 'linear-gradient(135deg, var(--saffron-soft), var(--gold-soft))',
          border: '1px solid var(--card-border)',
          boxShadow: 'var(--shadow-card)',
        }}
      >
        <div className="flex items-center gap-2 mb-3">
          <CheckCircle2 className="w-4 h-4" style={{ color: 'var(--saffron-primary)' }} aria-hidden="true" />
          <h2 className="text-sm font-bold uppercase tracking-wider" style={{ color: 'var(--saffron-primary)' }}>
            Our Core Commitments
          </h2>
        </div>
        <ul className="space-y-2">
          {[
            'Every Vivekananda quote is verified to volume and page.',
            'AI-generated text is always labeled and separated from authenticated quotes.',
            'We never simulate, impersonate, or claim to channel Swami Vivekananda.',
            'Crisis support resources are always visible and never hidden.',
            'User journal data stays on-device and is never transmitted.',
          ].map((item, i) => (
            <li key={i} className="flex items-start gap-2 text-sm" style={{ color: 'var(--text-primary)' }}>
              <span style={{ color: 'var(--saffron-primary)', marginTop: '2px' }} aria-hidden="true">✓</span>
              {item}
            </li>
          ))}
        </ul>
      </motion.div>

      {/* ── System Limitations ── */}
      <section aria-labelledby="limits-heading">
        <h2
          id="limits-heading"
          className="text-sm font-bold uppercase tracking-wider mb-4 flex items-center gap-2"
          style={{ color: 'var(--text-muted)' }}
        >
          <AlertCircle className="w-4 h-4" aria-hidden="true" />
          {t(lang, 'limits_title')}
        </h2>
        <div className="space-y-3">
          {LIMITATIONS.map((item, i) => (
            <motion.div
              key={item.title}
              custom={i}
              variants={cardVariants}
              initial="hidden"
              animate="visible"
              className="p-5 rounded-2xl"
              style={{
                background: 'var(--card-surface)',
                border: '1px solid var(--card-border)',
                boxShadow: 'var(--shadow-card)',
              }}
            >
              <div className="flex items-start gap-3">
                <span className="mt-0.5 shrink-0" style={{ color: item.color }}>
                  {item.icon}
                </span>
                <div>
                  <h3 className="text-sm font-bold mb-1" style={{ color: 'var(--text-primary)' }}>
                    {item.title}
                  </h3>
                  <p className="text-sm leading-relaxed" style={{ color: 'var(--text-muted)' }}>
                    {item.body}
                  </p>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      </section>

      {/* ── Citation Rules ── */}
      <section aria-labelledby="citation-heading">
        <h2
          id="citation-heading"
          className="text-sm font-bold uppercase tracking-wider mb-4 flex items-center gap-2"
          style={{ color: 'var(--text-muted)' }}
        >
          <Quote className="w-4 h-4" aria-hidden="true" />
          {t(lang, 'citation_title')}
        </h2>
        <div
          className="rounded-2xl overflow-hidden"
          style={{
            background: 'var(--card-surface)',
            border: '1px solid var(--card-border)',
            boxShadow: 'var(--shadow-card)',
          }}
        >
          {CITATION_RULES.map((rule, i) => (
            <div
              key={i}
              className="flex items-start gap-4 px-5 py-4"
              style={{ borderBottom: i < CITATION_RULES.length - 1 ? '1px solid var(--card-border)' : 'none' }}
            >
              <span
                className="w-6 h-6 rounded-full flex items-center justify-center text-xs font-bold shrink-0 mt-0.5"
                style={{ background: 'var(--saffron-soft)', color: 'var(--saffron-primary)' }}
                aria-hidden="true"
              >
                {i + 1}
              </span>
              <p className="text-sm leading-relaxed" style={{ color: 'var(--text-primary)' }}>
                {rule}
              </p>
            </div>
          ))}
        </div>
      </section>

      {/* ── Source Provenance ── */}
      <section aria-labelledby="provenance-heading">
        <h2
          id="provenance-heading"
          className="text-sm font-bold uppercase tracking-wider mb-4 flex items-center gap-2"
          style={{ color: 'var(--text-muted)' }}
        >
          <BookOpen className="w-4 h-4" aria-hidden="true" />
          {t(lang, 'provenance_title')}
        </h2>
        <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
          {SOURCES.map((src, i) => (
            <motion.a
              key={src.title}
              href={src.url}
              target="_blank"
              rel="noopener noreferrer"
              custom={i}
              variants={cardVariants}
              initial="hidden"
              animate="visible"
              className="flex items-start justify-between gap-3 p-4 rounded-xl transition-all hover:scale-[1.01] focus:outline-none focus-visible:ring-2 group"
              style={{
                background: 'var(--card-surface)',
                border: '1px solid var(--card-border)',
                boxShadow: 'var(--shadow-card)',
                textDecoration: 'none',
              }}
              aria-label={`${src.title} — opens in new tab`}
            >
              <div>
                <p className="text-sm font-semibold leading-snug" style={{ color: 'var(--text-primary)' }}>
                  {src.title}
                </p>
                <p className="text-xs mt-0.5" style={{ color: 'var(--text-muted)' }}>
                  {src.org}
                </p>
              </div>
              <ExternalLink
                className="w-3.5 h-3.5 shrink-0 mt-0.5 opacity-50 group-hover:opacity-100 transition-opacity"
                style={{ color: 'var(--saffron-primary)' }}
                aria-hidden="true"
              />
            </motion.a>
          ))}
        </div>
      </section>

      {/* ── Crisis Box ── */}
      <motion.div
        initial={{ opacity: 0 }}
        animate={{ opacity: 1 }}
        transition={{ delay: 0.5 }}
        className="p-5 rounded-2xl"
        style={{
          background: 'rgba(220,38,38,0.05)',
          border: '1px solid rgba(220,38,38,0.25)',
        }}
        role="complementary"
        aria-label="Crisis support information"
      >
        <p className="text-sm font-bold mb-1" style={{ color: 'var(--danger)' }}>
          🆘 {t(lang, 'crisis_title')}
        </p>
        <p className="text-sm leading-relaxed mb-3" style={{ color: 'var(--text-muted)' }}>
          {t(lang, 'crisis_text')}
        </p>
        <a
          href="tel:14416"
          className="inline-flex items-center gap-2 px-4 py-2 rounded-xl text-sm font-semibold text-white transition-all active:scale-95 focus:outline-none focus-visible:ring-2"
          style={{ background: 'var(--danger)' }}
          aria-label="Call Tele-MANAS crisis helpline: 14416"
        >
          📞 {t(lang, 'crisis_btn')}
        </a>
      </motion.div>

    </div>
  );
}
